# Generated by Django 3.0.14 on 2024-11-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcimc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='imc',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
