# Generated by Django 3.0.14 on 2024-11-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcimc', '0003_auto_20241125_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='historico',
            name='imc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historico',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10),
        ),
    ]
