# Generated by Django 3.0.14 on 2024-11-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcimc', '0005_historico_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='nome',
            field=models.CharField(default='Usuário', max_length=150),
        ),
    ]
